name: C/C++ CI Build

on:
  push:
    paths:
      - 2024_03_06_With_Workflow/**
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop
  workflow_dispatch:

jobs:
  Build:
    name: Leetcode Build Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: ${{ github.repository }} is cloned to the Runner
      run: echo "The ${{ github.repository }} repository has been cloned to the runner."

    - name: List files in the repository
      run: | 
        ls ${{ github.workspace }}

    # - name: Set up C++ Environment(By Default in Linux)
    #   run: sudo apt-get install gcc g++ make -y

    - name: Create a Folder to store all the cpp Files compiled Results
      run: |
        mkdir compiled_outputs
        cd 2024_03_06_With_Workflow
        ls

    - name: Find and Compile C++ files
      # g++ -c "$file" || { echo "Compilation failed for $file"; gh issue create --title "Compilation Failure" --body "Compilation failed for $file"; exit 1; }
      run: |
        cd 2024_03_06_With_Workflow
        ls
        files=$(find -name "*.cpp")
        for file in $files; do
          if ! g++ -c "$file"; then
            echo "Compilation failed for $file"
            gh auth login --with-token "${{ secrets.GITHUB_TOKEN }}"
            gh issue create --title "Compilation Failure" --body "Compilation failed for $file"
            exit 1;
          fi
        done
        ls
      env:
        file_extention: cpp
      

    # - name: Raise issue on compilation failure
    #   if: failure()
    #   run: |


    # - name: Build C++ Files
    # find -name "*.${{ env.file_extention }}" => Find C++ Files
    # # g++ -g $(find -name "*.${{ env.file_extention }}") -o leetcoder/
    #   run: |
    #     make
    #   env:
    #     file_extention: cpp

    # - name: Upload to Artifactory
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: leetcode-artifact
    #     path: leetcoder
    #     if-no-files-found: warn