name: Testing Github-Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v5 # For Javascript provided by Github
        id: create-comment # This is to get the access to the Output vars of the console log, e.g Get Results
        with:
          # context below is an object containing info abt workflow run
          script: | # This action allows to pass Javascript in scripts parameter.
            console.log(context); 
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "This is comment #4",
              body: "I created this using the github-script action!"
            });

            return "Some return data!";

      - name: Get result
        run: echo "${{steps.create-comment.outputs.result}}"