name: Job Output Testing

on:
  workflow_dispatch:

jobs:
  JOB1:
    
    runs-on: ubuntu-latest
    
    outputs: # Each Job can find an Output Variables which are defined before Steps
    # So we can Hardcode values here & can use them in another Jobs
      message: "This is a message coming from job 1" # Static Value
      url: ${{ steps.step1.outputs.url }} # Dynamic Value, i.e. Output of the Workflow
    steps:
      - uses: actions/checkout@v2

      - id: step1 # This set variable url
        name: send url to other job
        run: echo "::set-output name=url::https://pluralsight.com"

  JOB2:
    needs: JOB1
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{ needs.JOB1.outputs.message }} # Calling Job1 Output Variables

      - run: echo ${{ needs.JOB1.outputs.url }}
