name: Matrix Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy: 
      matrix: 
        os: [windows-latest, ubuntu-latest] 
        dot-net-version: [5.0.x]
        include: # Include below Job : 2+1 = 3 total Jobs
          - os: ubuntu-latest
            dot-net-version: 3.1.x
            
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dot-net-version }}
    
    - name: print os and version info
      run: echo "runner os ${{ runner.os }}, dotnet ${{ matrix.dot-net-version }}"
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore